services:
  vinder.comanda.subscriptions.infrastructure.mongo.database:
    container_name: "vinder.comanda.subscriptions.database"
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - vinder.comanda.subscriptions.infrastructure.mongo.database:/data/db

  vinder.infrastructure.identity.provider:
    container_name: "vinder.identity.provider"
    image: vinderio/identity.provider:latest
    env_file:
      - .env
    ports:
      - "5000:8080"
    depends_on:
      - vinder.comanda.subscriptions.infrastructure.mongo.database
    environment:
      Settings__Database__ConnectionString: ${MONGO_CONNECTIONSTRING}
      Settings__Database__DatabaseName: ${MONGO_DATABASENAME}
      Settings__Administration__Username: ${ADMIN_USERNAME}
      Settings__Administration__Password: ${ADMIN_PASSWORD}

volumes:
  vinder.comanda.subscriptions.infrastructure.mongo.database: